name: Build & Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: date >>data.txt
      - run: |
          # Run validation on data.txt
          cat data.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: data.txt
          message: "chore: append date to data.txt [skip ci]"
          default_author: github_actions
