name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  wait-for-renovate:
    name: Build & Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          # Wait for any pending Renovate PRs to complete
          sleep 30s
  test:
    name: Build & Test
    needs:
      - wait-for-renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Simulate linting source files
        run: |
          TZ='America/Los_Angeles' date '+%a %b %d %I:%M:%S %p %Z %Y' >>data.txt
      - name: Simulate testing the change
        run: |
          cat data.txt # placeholder for validation check
      - uses: EndBug/add-and-commit@43eaafb140bdacd4907fa7384fdd5cd271f58171
        with:
          add: .
          message: "chore: append date to data.txt [skip ci]"
          default_author: github_actions
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
