name: Build & Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - run: date >>data.txt
      - run: |
          cat data.txt # placeholder for validation check
      - uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: "chore: append date to data.txt [skip ci]"
          default_author: github_actions
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
